### ISSUE TITLE
Unresolved dependency when 'sbt test'

### ISSUE THREAD

**Issue by giacecco** [deanwampler/prog-scala-2nd-ed-code-examples#19]
Hi all, just started reading the book, did the ```sbt test``` as you suggested but get this. Apparently all dependencies download was successful. I'm running Oracle's JDK 1.8.0_102-b14. Thanks.

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.scala-lang#scala-library;2.10.4: configuration not found in org.scala-lang#scala-library;2.10.4: 'compile'. It was required from default#prog-scala-2nd-ed-code-examples-master-build;0.1-SNAPSHOT provided
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.4: configuration not found in org.scala-lang#scala-library;2.10.4: 'compile'. It was required from default#prog-scala-2nd-ed-code-examples-master-build;0.1-SNAPSHOT provided
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:213)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:122)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:121)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:116)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:104)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:51)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:60)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.withFileLock(Locks.scala:102)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:38)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:60)
	at sbt.IvySbt.withIvy(Ivy.scala:101)
	at sbt.IvySbt.withIvy(Ivy.scala:97)
	at sbt.IvySbt$Module.withModule(Ivy.scala:116)
	at sbt.IvyActions$.update(IvyActions.scala:121)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1161)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1159)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1182)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$73.apply(Defaults.scala:1180)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1184)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1179)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1187)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1152)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1130)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.scala-lang#scala-library;2.10.4: configuration not found in org.scala-lang#scala-library;2.10.4: 'compile'. It was required from default#prog-scala-2nd-ed-code-examples-master-build;0.1-SNAPSHOT provided
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

**Comment by deanwampler** [comment]
I'm confused by the error and by the expression in the error message, `It was required from default#prog-scala-2nd-ed-code-examples-master-build;0.1-SNAPSHOT`. I don't recall using a version number like `0.1-SNAPSHOT` in the `build.sbt` (it is currently `2.1`). Also, I dropped 2.10 support long before I finished the book. 

SBT still uses 2.10, I believe, but it looks like you got past booting up SBT. As a sanity check, if you just run the `sbt` command without arguments *in the root directory of this project*, does it start fine and put you at the `sbt` prompt?

Where did you get the code examples? Wherever you got them, you should check out the latest code from this repo and use that. I just pushed a bug fix a few minutes ago to `build.sbt`, but it doesn't affect this error. 

Let me know if you need more help or you are able to resolve the issue. Thanks.

**Comment by giacecco** [comment]
Hi. 

Running ```sbt``` without arguments in the root directory of this project gives me the same issue I've posted before.

Running ```bst``` in any other folder has no issues, I get the prompt. 

```build.sbt``` seems to be the one you're referring, to, its top lines are:

```
[giacecco@giaceccos-linux prog-scala-2nd-ed-code-examples-master]$ more build.sbt 
name := "Programming Scala, Second Edition - Code examples"
version := "2.1"
organization := "org.programming-scala"
scalaVersion := "2.11.7"
(...)
```

I got the code examples from GitHub, choosing the download zip feature.

Any advice?

**Comment by giacecco** [comment]
Could it be that the latest scala packages available for Fedora are version 2.10.4, but your project requires 2.11.7?

**Comment by giacecco** [comment]
I've removed the sbt packages and installed from the sbt website as described at http://www.scala-sbt.org/download.html . That worked. Would you suggest it is good practice to ignore the Linux distro's Scala packages and use this method instead?

**Comment by deanwampler** [comment]
Normally SBT downloads its own Scala libraries, as needed, so technically, it shouldn't matter what's installed on your machine. However, it appears that your installed version got used somehow, perhaps through your `PATH` or something like that. Anyway, I'm glad it's working now.

If you need a standalone Scala version to play with, I do recommend downloading the latest version from http://www.scala-lang.org/

dean
